### ISSUE TITLE
macOS builds broken

### ISSUE THREAD

**Issue by stephenulmer** [Parallels/packer-examples#55]
https://github.com/Parallels/packer-examples/commit/79d5985c3bedb04b35a0b44dd953ada6ca69fa50 is a huge step forward for the user and building for multiple versions of macOS!

Unfortunately, when validating variables:

```
Error: Unknown source parallels-macvm.sonoma

  on build.pkr.hcl line 1:
  (source code not available)

Known: [parallels-ipsw.monterey parallels-ipsw.sequoia parallels-ipsw.sonoma
parallels-ipsw.ventura]
```

The file `provisioner.pkr.hcl` defines variable `version_source`. Most of the values have *macvm* in them, and I'm guessing it's supposed to be *ipsw*.

I don't really understand how this part works, but I think that I could start the build with an existing virtual machine, and somehow reference it's name, rather than using the macOS installer to create a brand new one?

At any rate, there is now #54 in case that is actually correct. I tested it and it seems to work.

**Comment by cjlapao** [comment]
@stephenulmer Yes, that is correct. It should be ipsw.

This exists because we use some "AI" to automate the Mac installation. However, because every Mac OS release is slightly different in terms of text and screens, we need to pass different instructions to our agents to tell them what screens to expect.

Hence that strange code. what you need to add is the variable version and say what version are you going to install
for example:

```hcl
version="monterey"
machine_name = "macOs-ventura-12.6"
machine_specs = {
  cpus   = 4,
  memory = 8192,
}

addons = [
]
ipsw_url= "https://updates.cdn-apple.com/2022FallFCS/fullrestores/012-40537/0EC7C669-13E9-49FB-BD64-9EECC1D174B2/UniversalMac_12.6_21G115_Restore.ipsw"
ipsw_checksum = "5113f8d3c77fd725ea6357ced5764bc57183d2d388492c58c46ff2729d0658e5"
create_vagrant_box = false
```

we are passing the version as Monterey and then we set the ipsw for download, this will then select the right source and send the right instructions to the agent.

if you want to use an already existing macvm, you can but that will use the macVM builder and you just need to pass the path for that macVM instead of the ipsw.

Hope this makes sense, if not let me know

**Comment by stephenulmer** [comment]
The OCR bit is seriously cool! It will occasionally get stuck for me, but I think that's because when it's building in the background, sometimes I cycle through my windows and put that one in focus for a second.

At any rate, thanks for the opportunity to learn more about Packer, and for putting up with my Git -- I don't get to collaborate too much and this is a good experience for me.

**Comment by cjlapao** [comment]
@stephenulmer I am the one that need to thank you, you help us improve the packer scripts for everyone, please feel free to keep helping  and if you need any further help just let me know
